### ISSUE TITLE
p-multiSelect: checkbox/label not aligned correctly  

### ISSUE THREAD

**Issue by iguissouma** [primefaces/ultima#15]
![2016-12-22_12h36_48](https://cloud.githubusercontent.com/assets/9085108/21424552/e03202c4-c843-11e6-8e1c-7a1748d8e8aa.png)

primeng version:1.1.1
ultimang version:1.0.3

**Comment by mertsincan** [comment]
Please use this repo for ultima-ng; https://github.com/primefaces/ultima-ng/issues
