### ISSUE TITLE
A p: datatable selectable inside a p: dialog not work

### ISSUE THREAD

**Issue by maxlanechagas** [primefaces/ultima#23]
I'm implementing a p: datatable selectionMode = "single" inside a p: dialog. The even lines are not selectable, and clicking on these lines (the pairs) does not have the colors of a selected line.

**Comment by mertsincan** [comment]
I couldn't replicate this issue. 

Screenshot;

![dialog_example](https://cloud.githubusercontent.com/assets/11868120/25085375/80eb25fc-236a-11e7-9542-ff17ff731f7a.PNG)

Please create an issue on Ultima Forum and attach a sample page into it; https://forum.primefaces.org/viewforum.php?f=42
